name: linktree_demo_clone
description: linktree clone

version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^5.4.1
  cupertino_icons: ^0.1.2
  transparent_image: ^1.0.0
  firebase_core: ^0.4.3+1
  sentry: ^3.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Karla
      fonts:
        - asset: fonts/Karla-Regular.ttf
        - asset: fonts/Karla-Italic.ttf
          style: italic
        - asset: fonts/Karla-Bold.ttf
          weight: 900
        - asset: fonts/Karla-BoldItalic.ttf
          style: italic
          weight: 900
